### ISSUE TITLE
Shields.io CPP Logo

### ISSUE THREAD

**Issue by kyechan99** [wookyoungkim/wookyoungkim#1]
# CPP 로고

## 기존
![](https://img.shields.io/badge/C++-00599C?style=flat-square&logo=cplusplus&logoColor=white)
```
https://img.shields.io/badge/C++-00599C?style=flat-square&logo=cplusplus&logoColor=white
```

## 변경
`%2B` 는 + 를 의미합니다 : [urlencoding](https://www.degraeve.com/reference/urlencoding.php)
![](https://img.shields.io/badge/C++-00599C?style=flat-square&logo=C%2B%2B&logoColor=white)
```
https://img.shields.io/badge/C++-00599C?style=flat-square&logo=C%2B%2B&logoColor=white
```

**Comment by wookyoungkim** [comment]
ㄷ ㅔ박감사합니다 ㅠㅠㅠㅠㅠㅠㅠ 좋은 오픈소스 제공해주셔서 덕분에 깃프로필 예쁘게 꾸몄어요 ㅎㅎ.. 감사합니다
